apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-replication-controller
  labels: 
    app: myapp
spec:
  replicas: 2
  selector:
    app: myapp
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx

